# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 316a7141af445a306a9a8f8b0e712ea733c44af7bffcba588e325db94c0ddbccf11f5fb08c897ad0632abbf033beb35a5753b5aafc27aaed29a00ee74b953cd2

test:
  secret_key_base: 439439748d25df4563245ca58b1c30e55ee6a7c86f63c36e76a2f4f0fe81ae27ca00a82395d16cdfb9f604e9f0b9e5ba9d9c8a2ce57c0bb80931b9b6b0a93cdd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
